security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:      "%env(resolve:APP_SECRET)%"
                path:     /
            logout_on_user_change: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        sourceml_users:
            entity:
                class: Sourceml\Entity\App\User

    encoders:
        Sourceml\Entity\App\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_USER }
